### ISSUE TITLE
Unable to install in Docker

### ISSUE THREAD

**Issue by mariushosting** [BetaPictoris/flagdown#30]
I'm continue to have issue with Docker. Can't install.

docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "flagdown": executable file not found in $PATH: unknown.)](docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "flagdown": executable file not found in $PATH: unknown.)

**Comment by BetaPictoris** [comment]
Hello again! Thanks for the new issue, and I apologize for the Docker issues. c0d716e9a37cbc6196997c48e9a126f696c26759 should fix the `$PATH` issue, although Flagdown requires the `libdl` library, but Busybox and Alpine don't seem to have it included in their Docker images. I'll keep working on it and update you when it's fixed!

**Comment by BetaPictoris** [comment]
Debian includes `libdl`, so we have a temporary fix.

**Comment by BetaPictoris** [comment]
Fixed in [v0.1.3b (Naitaka)](https://github.com/BetaPictoris/flagdown/releases/tag/v0.1.3b), CD job is done, enjoy in [latest](https://github.com/BetaPictoris/flagdown/pkgs/container/flagdown/58941128?tag=latest)!
